name: Upload Zipped Python App to S3

on:
  push:
    branches:
      - main   

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   

      - name: Zip Python app
        run: |
          zip app.zip app.py
          echo "Zipped app.py into app.zip"

      - name: Upload ZIP file to S3
        run: |
          aws s3 cp app.zip s3://your-s3-bucket-name/python-apps/app.zip
          echo "Uploaded app.zip to S3 bucket"
          
